### ISSUE TITLE
NPM ERR running script: SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by regisphilibert** [chrisdmacrae/atomic-algolia#11]
I am using an .env file (tried with and without quotes)

I'm starting here in case I am doing something wrong, but let me know if think it deserves a GitHub Issue

You can check the code [here (search branch)](https://github.com/regisphilibert/benmerde/tree/search)

Here is the log: 
[2018-03-06T17_03_06_414Z-debug.log](https://github.com/chrisdmacrae/atomic-algolia/files/1786108/2018-03-06T17_03_06_414Z-debug.log)

**Comment by regisphilibert** [comment]
This is solved by updating Node obviously. Sorry about that...

**Comment by chrisdmacrae** [comment]
Thanks Regis! I've updated the package to reference the proper node number.
