### ISSUE TITLE
getRemoteIndex does not seem to resolve on > 1000 entries indices

### ISSUE THREAD

**Issue by regisphilibert** [chrisdmacrae/atomic-algolia#16]
It seems `getRemoteIndex` does not resolve with indices holding over 1000 entries.

Therefore, `oldIndex` remains `undefined` and the script will then assume there is no entry in the `oldIndex` and push every entries from the `newIndex` to Algolia without checking for changes first.

**Comment by chrisdmacrae** [comment]
@regisphilibert this will be fixed today in `0.3.18`
