### ISSUE TITLE
[BUG] ReferenceError: hits is not defined

### ISSUE THREAD

**Issue by sepukus** [chrisdmacrae/atomic-algolia#31]
## Description
  Fix ReferenceError in getRemoteIndex.js

ReferenceError: hits is not defined
atomic-algolia\lib\utils\getRemoteIndex.js:50:10

## System information
atomic-algolia version: 0.3.18
node-version: 10.15.3

**Comment by varun-raj** [comment]
https://github.com/chrisdmacrae/atomic-algolia/pull/32
